### ISSUE TITLE
Update from Podfile fails

### ISSUE THREAD

**Issue by ibuprofane** [flowsprenger/RxLifx-Swift#27]
Hello,

I've been integrating with this code through my Podfile:

pod 'RxLifx', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git'
pod 'LifxDomain', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git'
pod 'RxLifxApi', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git'

With the recent changes, the code now fails to compile with 8 errors.

To fix, I am using the previous build by commit hash:
  pod 'RxLifx', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git', :commit => 'd0e777e29842289a3cd534a09b8f0a4704b29d8c'
  pod 'LifxDomain', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git', :commit => 'd0e777e29842289a3cd534a09b8f0a4704b29d8c'
  pod 'RxLifxApi', :git => 'https://github.com/flowsprenger/RxLifx-Swift.git', :commit => 'd0e777e29842289a3cd534a09b8f0a4704b29d8c'

**Comment by flowsprenger** [comment]
@ibuprofane thanks for reporting,  I fix the podspecs, let me know in case you still encounter the issue
