### ISSUE TITLE
Multicast Networking entitlement required to use library

### ISSUE THREAD

**Issue by ibuprofane** [flowsprenger/RxLifx-Swift#29]
Hello,

As of iOS 14.6, the Multicast Networking entitlement is required for light discovery to work correctly. This requires adding the com.apple.developer.networking.multicast key/value to the project .entitlement file. It also requires special permission from Apple, linked to your developer account, that can be requested here: https://developer.apple.com/contact/request/networking-multicast 

In your request you must include specifics for how you plan to use the entitlement, including the discovery broadcast address/port (255.255.255.255:56700). Note that it may take 2 weeks for approval to be granted.

More details can be found here: https://developer.apple.com/forums/thread/663271

**Comment by flowsprenger** [comment]
Thanks for reporting @ibuprofane I will add this to the Readme in a second.
